server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/css,application/javascript
  forward-headers-strategy: FRAMEWORK
spring:
  application:
    name: marcura-miniurl